apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flaskapp
  namespace: flaskapp

spec:
  replicas: 2

  selector:
    matchLabels:
      app: python-flaskapp

  template:
    metadata:
      labels:
        app: python-flaskapp

    spec:
      containers:
        - name: python-flaskapp
          image: turkswerks/python-flaskapp:11-54f3cc2
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
